### ISSUE TITLE
Players walk weird, no animations.

### ISSUE THREAD

**Issue by Erdrag** [Whitetigerswt/gtasa_crashfix#42]
1. When i install crashes, players ingame, walk/run around without the animation, so it looks like they either floating, or lagging forward.

What may be the problem? and how to solve it.

**Comment by Whitetigerswt** [comment]
Might be related to #41 does this happen on 0.3.7?

**Comment by Erdrag** [comment]
> Might be related to #41 does this happen on 0.3.7?

I'm using the 0.3.7-R3 version

**Comment by Erdrag** [comment]
I have not tried the other samp versions.

**Comment by Sleeper1312** [comment]
This also happens in 0.3dl and I was hoping there would be some sort of fix soon as since I haven't had crashes installed. I run into a lot of different problems that I did not have from before the updates.

For 0.3dl other players just walk but instead of fully beginning to walk it cancels the animation and does this over and over again. It's look really bad and makes it nearly impossible to even know when someone is shooting at you as well lol. Hopefully this helps a bug fix soon!

**Comment by Whitetigerswt** [comment]
I'm gonna try to look into this, this week hopefully.
