### ISSUE TITLE
High FPS bug / question

### ISSUE THREAD

**Issue by xmpl666** [Whitetigerswt/gtasa_crashfix#54]
On high FPS my character is twitching when I shot without bugs (300+ fps). As I know, this bug is difficult / impossible to fix. I have a question about the new crashes.asi. Is it possible to set a frame limiter there that I want? To exempel if I want to put the limiter on 120, 150 or 200 fps.

**Comment by xmpl666** [comment]
And I also want to thank you for crashes.asi.

**Comment by Whitetigerswt** [comment]
I think you should use an external program to limit your FPS. I don't know if there's any newer programs around, but when I was active in SA-MP, many would use Dxtory to limit FPS. Maybe OBS or another newer program can do it that is better supported though.

I would use one of those programs because they would without a doubt work better than anything I could come up with.
